//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IVA.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class IVADBEntities : DbContext
    {
        public IVADBEntities()
            : base("name=IVADBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<tbl_Control_Types> tbl_Control_Types { get; set; }
        public DbSet<tbl_Product_Images> tbl_Product_Images { get; set; }
        public DbSet<tbl_Product_Reviews> tbl_Product_Reviews { get; set; }
        public DbSet<tbl_Product_Specs> tbl_Product_Specs { get; set; }
        public DbSet<tbl_Products> tbl_Products { get; set; }
        public DbSet<tbl_Spec_items> tbl_Spec_items { get; set; }
        public DbSet<tbl_Specs> tbl_Specs { get; set; }
        public DbSet<tbl_Users> tbl_Users { get; set; }
    }
}
