//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IVA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Products
    {
        public tbl_Products()
        {
            this.tbl_Product_Images = new HashSet<tbl_Product_Images>();
            this.tbl_Product_Reviews = new HashSet<tbl_Product_Reviews>();
            this.tbl_Product_Specs = new HashSet<tbl_Product_Specs>();
        }
    
        public long ID { get; set; }
        public string Name { get; set; }
        public bool IsActive { get; set; }
        public string Remarks { get; set; }
        public decimal Rate { get; set; }
        public decimal OurRate { get; set; }
        public long Stock { get; set; }
    
        public virtual ICollection<tbl_Product_Images> tbl_Product_Images { get; set; }
        public virtual ICollection<tbl_Product_Reviews> tbl_Product_Reviews { get; set; }
        public virtual ICollection<tbl_Product_Specs> tbl_Product_Specs { get; set; }
    }
}
