//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IVA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Product_Reviews
    {
        public long ID { get; set; }
        public System.DateTime Date { get; set; }
        public long ProductID { get; set; }
        public string Description { get; set; }
        public bool IsActive { get; set; }
        public long UserID { get; set; }
        public int Point { get; set; }
    
        public virtual tbl_Products tbl_Products { get; set; }
        public virtual tbl_Users tbl_Users { get; set; }
    }
}
