//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IVA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Specs
    {
        public tbl_Specs()
        {
            this.tbl_Product_Specs = new HashSet<tbl_Product_Specs>();
            this.tbl_Spec_items = new HashSet<tbl_Spec_items>();
        }
    
        public long ID { get; set; }
        public string Name { get; set; }
        public bool IsActive { get; set; }
        public long ControlType { get; set; }
        public string Remarks { get; set; }
    
        public virtual tbl_Control_Types tbl_Control_Types { get; set; }
        public virtual ICollection<tbl_Product_Specs> tbl_Product_Specs { get; set; }
        public virtual ICollection<tbl_Spec_items> tbl_Spec_items { get; set; }
    }
}
