//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IVA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Users
    {
        public tbl_Users()
        {
            this.tbl_Product_Reviews = new HashSet<tbl_Product_Reviews>();
        }
    
        public long ID { get; set; }
        public bool IsActive { get; set; }
        public string Remarks { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string email { get; set; }
        public string Phone { get; set; }
        public string DisplayName { get; set; }
        public string ProfilePicPath { get; set; }
    
        public virtual ICollection<tbl_Product_Reviews> tbl_Product_Reviews { get; set; }
    }
}
